plugins:
  - jekyll-twitter-plugin
title: The things network community Mongolia
theme: jekyll-theme-minimal
description: > # this means to ignore newlines until "baseurl:"
  s

twitter_username: ttn_mongolia
github_username:  erdemnet